/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaison J
 */
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

public class AdminScreen extends javax.swing.JFrame {
     public static final String DBURL="jdbc:oracle:thin:@JB4ROGUE:1521:XE";
      public static final String DBUSER="system";
       public static final String DBPASS="student";
       public static int b;

    /**
     * Creates new form AdminScreen
     */
    public AdminScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jLabel2.setText("jLabel2");

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("BACK<<");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 660));
        setMinimumSize(new java.awt.Dimension(800, 660));
        setPreferredSize(new java.awt.Dimension(800, 660));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(null);

        jButton3.setBackground(new java.awt.Color(0, 51, 51));
        jButton3.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Log Out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(0, 5, 790, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 170, 790, 40);

        jLabel6.setFont(new java.awt.Font("Swis721 Blk BT", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CHANGE MOVIES");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(580, 180, 260, 150);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/iStock_000062233330_Full.jpg"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 210, 400, 410);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/movies-red.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(390, 210, 410, 410);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/3eed8b8c.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 810, 170);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/geometric-white-hexagonal-vector-seamless-pattern-tile-45608163.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 170, 800, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        int b;
        try{
            int count=0;
         Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);

 

        Statement statement = con.createStatement();
         ResultSet rs = statement.executeQuery("  select MOVIE_ID,sum(total) from bill1 group by movie_id order by movie_id");
        while(rs.next())
        { b=0;
            if(rs.getInt(1)==100)
        {   count++;
            dataset.setValue(rs.getInt(2), "PROFIT", "100");
        }
         if(rs.getInt(1)==101)
        {   if(count==0)
        {   dataset.setValue(0, "PROFIT", "100");
            dataset.setValue(rs.getInt(2), "PROFIT", "101");
            count++;
        }
        else
        {dataset.setValue(rs.getInt(2), "PROFIT", "101");
            count++;}
        }
         if(rs.getInt(1)==102)
        {if(count==1)
        {   dataset.setValue(0, "PROFIT", "101");
            dataset.setValue(rs.getInt(2), "PROFIT", "102");
            b=1;
        }
        else if(count==0)
        {   dataset.setValue(0, "PROFIT", "100"); 
            dataset.setValue(0, "PROFIT", "101");
            dataset.setValue(rs.getInt(2), "PROFIT", "102");
            b=2;
        }
        else
        {dataset.setValue(rs.getInt(2), "PROFIT", "102");
        b=3;
        }
        }
         if(rs.getInt(1)==103)
        {
            if(count==0){
              dataset.setValue(0, "PROFIT", "100"); 
            dataset.setValue(0, "PROFIT", "101");
            dataset.setValue(0, "PROFIT", "102");
            dataset.setValue(rs.getInt(2), "PROFIT", "103");
        }
            else if(count==1&&b==1)
                
            {    
                dataset.setValue(0, "PROFIT", "101");
                 dataset.setValue(rs.getInt(2), "PROFIT", "103");
                
                
            }
             else if(count==1&&b==2)
                
            {    dataset.setValue(0, "PROFIT", "100");
                dataset.setValue(0, "PROFIT", "101");
                 dataset.setValue(rs.getInt(2), "PROFIT", "103");
                
                
            }
             else 
             {    dataset.setValue(rs.getInt(2), "PROFIT", "103");
             }
        }
        }
        
         
       
        JFreeChart chart= ChartFactory.createBarChart("SALES","MOVIE_ID", "PROFIT", dataset, PlotOrientation.VERTICAL, false, true, false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.black);
        p.setBackgroundPaint(Color.blue);
        ChartFrame f=new ChartFrame("simple bar chart",chart);
        f.setVisible(true);
        f.setSize(800,800);
        
        
        
        
        
        
        }
        catch(Exception e)
        {e.printStackTrace();}
        
        
        
        
        
        
        
        
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        ChangeMovies f = new ChangeMovies();
        f.show();
        this.hide();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        UserLogin f = new UserLogin();
        f.show();
        this.hide();
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
