/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaison J
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class Refershments extends javax.swing.JFrame {
    public static int u;
    public static int rprice;
    public static int done = 0 ;
 
    /**
     * Creates new form Refershments
     */
    public Refershments() {
        initComponents();
    }
 public Refershments(int a) {
        initComponents();
        u=a;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 680));
        setMinimumSize(new java.awt.Dimension(800, 680));
        setPreferredSize(new java.awt.Dimension(800, 680));
        getContentPane().setLayout(null);

        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 220, 60, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/3eed8b8c.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 810, 170);

        jLabel9.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 560, 90, 30);

        jLabel8.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel8.setText("Total");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 560, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEM", "QTY"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(490, 230, 300, 320);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Caramel popcorn", "Cheese popcorn", "Butter popcorn", "" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(160, 250, 150, 22);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "7-UP", "Pepsi", "Miranda" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(160, 310, 160, 22);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "With Cheese Dip", "With Salsaa Dip", "Whith Jlapeno Sauce" }));
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(160, 380, 160, 22);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Chocolate", "Vanilla", "Strawberry", "Mint" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(160, 430, 160, 22);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(340, 250, 50, 30);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        getContentPane().add(jSpinner2);
        jSpinner2.setBounds(350, 310, 50, 30);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        jSpinner3.setToolTipText("");
        getContentPane().add(jSpinner3);
        jSpinner3.setBounds(340, 380, 50, 30);

        jSpinner4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));
        getContentPane().add(jSpinner4);
        jSpinner4.setBounds(340, 430, 50, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setLabel("Order");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 500, 140, 25);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setLabel("Proceed To Billing");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(570, 580, 190, 30);

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel1.setText("Popcorn");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 250, 90, 30);

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel3.setText("Nachos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 380, 70, 16);

        jLabel6.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel6.setText("Drinks");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 310, 90, 16);

        jLabel7.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel7.setText("Ice-Cream");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 430, 80, 16);

        jLabel2.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/geometric-white-hexagonal-vector-seamless-pattern-tile-45608163.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 170, 800, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String popcorn = "" ;
        String Drinks = "" ;
        String Nachos = "" ;
        String ice_cream = "" ;
        int qty1=(int)jSpinner1.getValue();
        int qty2=(int)jSpinner1.getValue();
        int qty3=(int)jSpinner1.getValue();
        int qty4=(int)jSpinner1.getValue();
        
        if(jComboBox1.getSelectedItem().toString() != "None")
        {
            model.addRow(new Object[]{jComboBox1.getSelectedItem().toString(),jSpinner1.getValue()});
            done = 1 ;
            
        }
        if(jComboBox2.getSelectedItem().toString() != "None")
        {
            model.addRow(new Object[]{jComboBox2.getSelectedItem().toString(),jSpinner2.getValue()});
            done = 1 ;
        }
        if(jComboBox3.getSelectedItem().toString() != "None")
        {
            model.addRow(new Object[]{jComboBox3.getSelectedItem().toString(),jSpinner3.getValue()});
            done = 1 ;
        }
        if(jComboBox4.getSelectedItem().toString() != "None")
        {
            model.addRow(new Object[]{jComboBox4.getSelectedItem().toString(),jSpinner4.getValue()});
            done = 1 ;
        }
        int total = (qty1*30+qty2*25+qty3*15+qty4*20);
        jLabel9.setText(String.valueOf(total));
        jButton1.setEnabled(false);
        rprice = total ;
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        if(done == 1 )
        { Billing one = new Billing(u,rprice);
        one.show();
        this.hide();     
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Have some Refreshments", "INVALID", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Refershments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Refershments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Refershments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Refershments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Refershments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
