
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jaison J
 */
public class UserLogin extends javax.swing.JFrame {
          public static final String DBURL="jdbc:oracle:thin:@JB4ROGUE:1521:XE";
      public static final String DBUSER="system";
       public static final String DBPASS="student";
       public static int found=0;
       public static int u;

    /**
     * Creates new form UserLogin
     */
    public static int user_id;
    public UserLogin() {
        found=0;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(800, 507));
        setMinimumSize(new java.awt.Dimension(800, 507));
        getContentPane().setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Sign Up");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(690, 180, 90, 25);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Don't Have An Account");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 180, 210, 21);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 380, 63, 25);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(370, 300, 180, 22);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Customer");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(310, 340, 83, 25);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Admin");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(410, 340, 65, 25);

        jLabel7.setText("Choose One of the Following");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(130, 340, 180, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 260, 180, 30);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 300, 100, 20);

        jLabel4.setText("Username/Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 260, 180, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/3eed8b8c.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 170);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/theatremanagement/1157b6fd85f1ff2.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setPreferredSize(new java.awt.Dimension(800, 333));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 170, 800, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jRadioButton1.isSelected() == true)
        {
             try{ Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);

         Statement statement = con.createStatement();
          ResultSet rs = statement.executeQuery("SELECT name,password,user_id FROM user_login "); 
          while(rs.next())
          {String s1=rs.getString(1);
          String s2=rs.getString(2);
           
          if(s1.equals(jTextField2.getText())&&s2.equals(jPasswordField1.getText()) )
          { found=1;
          u=rs.getInt(3);
              MovieBooking f = new MovieBooking(u);
            f.show();
            this.hide();
          }
          }
          if(found==0)
          { if(found==0)
          {JOptionPane.showMessageDialog(null, "wrong user_name or password!", "INVALID", JOptionPane.INFORMATION_MESSAGE);
          }}
         
         
  
        }
        catch(Exception e)
        {e.printStackTrace();}
          
           
                   
        }
        
        else if(jRadioButton2.isSelected() == true)
        {
             try{Connection con = DriverManager.getConnection(DBURL, DBUSER, DBPASS);
                 Statement statement = con.createStatement();

       ResultSet rs = statement.executeQuery("SELECT name,password FROM admin "); 
          if(rs.next())
          {String s1=rs.getString(1);
          String s2=rs.getString(2);
           
          if(s1.equals(jTextField2.getText())&&s2.equals(jPasswordField1.getText()) )
          { AdminScreen f = new AdminScreen();
            f.show();
            this.hide();
          }
          else
          {JOptionPane.showMessageDialog(null, "wrong user_name or password", "INVALID", JOptionPane.INFORMATION_MESSAGE);
          }
        
        
        }
             }
             catch(Exception e)
             {e.printStackTrace();}
            
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SignUp t = new SignUp();
        t.show();
        this.hide();
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
   
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
